[[social]]
    identifier = "Whatsapp"
    name       = "Whatsapp"
    url        = "https://wa.me/551992400792"
    newtab = true
    [social.params]
        icon = "whatsapp"
[[social]]
    identifier = "LinkedIn"
    name       = "LinkedIn"
    url        = "https://linkedin.com/in/geraldohomero"
    newtab = true
    [social.params]
        icon = "linkedin"
[[social]]
    identifier = "Email"
    name       = "Email"
    url        = "mailto:geraldohomero+universitas@pm.me"
    newtab = true
    [social.params]
        icon = "email"